CREATE TABLE "platforms" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE,
  "slug" varchar
);

CREATE TABLE "profiles" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar
);

CREATE TABLE "profile_platform_accounts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "profile_id" int,
  "platform_id" int,
  "external_user_id" varchar,
  "profile_url" varchar
);

CREATE TABLE "games" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "igdb_id" int UNIQUE,
  "name" varchar,
  "cover_image" varchar,
  "icon_image" varchar,
  "logo_image" varchar
);

CREATE TABLE "platform_games" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" int,
  "platform_id" int,
  "external_game_id" varchar
);

CREATE TABLE "achievements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "platform_game_id" int,
  "external_achievement_id" varchar,
  "name" varchar,
  "description" text,
  "icon_image" varchar,
  "icon_locked_image" varchar
);

CREATE TABLE "profile_games" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "profile_id" int,
  "platform_game_id" int,
  "playtime_minutes" int,
  "last_played" timestamp
);

CREATE TABLE "profile_achievements" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_game_id" int,
  "achievement_id" int,
  "achieved" boolean,
  "unlock_time" timestamp
);

CREATE UNIQUE INDEX ON "profile_platform_accounts" ("profile_id", "platform_id");

CREATE UNIQUE INDEX ON "platform_games" ("platform_id", "external_game_id");

CREATE UNIQUE INDEX ON "achievements" ("platform_game_id", "external_achievement_id");

CREATE UNIQUE INDEX ON "profile_games" ("profile_id", "platform_game_id");

CREATE UNIQUE INDEX ON "profile_achievements" ("user_game_id", "achievement_id");

COMMENT ON COLUMN "games"."igdb_id" IS 'nullable for RetroAchievements';

ALTER TABLE "profile_platform_accounts" ADD FOREIGN KEY ("profile_id") REFERENCES "profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "profile_platform_accounts" ADD FOREIGN KEY ("platform_id") REFERENCES "platforms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "platform_games" ADD FOREIGN KEY ("game_id") REFERENCES "games" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "platform_games" ADD FOREIGN KEY ("platform_id") REFERENCES "platforms" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "achievements" ADD FOREIGN KEY ("platform_game_id") REFERENCES "platform_games" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "profile_games" ADD FOREIGN KEY ("profile_id") REFERENCES "profiles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "profile_games" ADD FOREIGN KEY ("platform_game_id") REFERENCES "platform_games" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "profile_achievements" ADD FOREIGN KEY ("user_game_id") REFERENCES "profile_games" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "profile_achievements" ADD FOREIGN KEY ("achievement_id") REFERENCES "achievements" ("id") DEFERRABLE INITIALLY IMMEDIATE;
